//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace .Domain.Implementation.Schemas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class 
        JsonSchemas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonSchemas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(".Domain.Implementation.Schemas.JsonSchemas", typeof(JsonSchemas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;http://example.com/example.json&quot;,
        ///  &quot;type&quot;: &quot;object&quot;,
        ///  &quot;definitions&quot;: {},
        ///  &quot;$schema&quot;: &quot;http://json-schema.org/draft-06/schema#&quot;,
        ///  &quot;properties&quot;: {
        ///    &quot;type&quot;: {
        ///      &quot;$id&quot;: &quot;/properties/type&quot;,
        ///      &quot;type&quot;: &quot;string&quot;,
        ///      &quot;title&quot;: &quot;The Type Schema&quot;,
        ///      &quot;description&quot;: &quot;Type of form (Registration, Interest, etc.)&quot;,
        ///      &quot;default&quot;: &quot;&quot;,
        ///      &quot;examples&quot;: [
        ///        &quot;ABCDEF&quot;
        ///      ]
        ///    },
        ///    &quot;group&quot;: {
        ///      &quot;$id&quot;: &quot;/properties/group&quot;,
        ///      &quot;type&quot;: &quot;string&quot;,
        ///      &quot;title&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UpsertFormSchema {
            get {
                return ResourceManager.GetString("UpsertFormSchema", resourceCulture);
            }
        }
    }
}
